### ISSUE TITLE
[NOT AN ISSUE]  - DistroBox - Missing python3-gobject-base dependency

### ISSUE THREAD

**Issue by Zeglius** [H3rz3n/davinci-helper#15]
Seems davinci-helper doesnt work out of the box in a distrobox container (fedora 41).
```
📦[zeglius@distrobox-dKTcWwebJz ~]$ davinci-helper 
Traceback (most recent call last):
  File "/usr/bin/davinci-helper", line 5, in <module>
    from davinci_helper.main import main
  File "/usr/lib/python3.13/site-packages/davinci_helper/main.py", line 10, in <module>
    import sys, gi, os, threading, gettext, locale, subprocess
ModuleNotFoundError: No module named 'gi'
```

Installing `python3-gobject-base` solves it

**Comment by Malix-Labs** [comment]
_@H3rz3n could you close this issue as "not planned" instead of "completed" please? :)_
