### ISSUE TITLE
[BUG] No module named 'moviepy.editor'

### ISSUE THREAD

**Issue by Chevek** [H3rz3n/davinci-helper#19]
copr is currently broken on Fedora 41:

```
$ davinci-helper 
Traceback (most recent call last):
  File "/usr/bin/davinci-helper", line 5, in <module>
    from davinci_helper.main import main
  File "/usr/lib/python3.13/site-packages/davinci_helper/main.py", line 32, in <module>
    from .functions.gui.function_5_gui import function_5_class
  File "/usr/lib/python3.13/site-packages/davinci_helper/functions/gui/function_5_gui.py", line 36, in <module>
    from ..logic import conversion_settings
  File "/usr/lib/python3.13/site-packages/davinci_helper/functions/logic/conversion_settings.py", line 13, in <module>
    from moviepy.editor import VideoFileClip
ModuleNotFoundError: No module named 'moviepy.editor'
```

**Comment by TarsiSurdi** [comment]
I'm facing the same issue here!

**Comment by H3rz3n** [comment]
Hi, thank you for using DaVinci Helper. You are experiencing a very strange bug. MoviePy python module is supposed to be installed after the installation of DaVinci Helper as post-install script.

You can solve this issue installing it manually with PIP using `pip install moviepy`.

Can you please provide me more info about your Fedora config? Did you have installed the app from the COPR repository ?

**Comment by TarsiSurdi** [comment]
Yep, I've installed it through the COPR repo. I noticed some weird warning logs, this is what I get after uninstalling it and trying again: 
```
[1/2] davinci-helper-0:2.1.0-1.noarch                                                  100% |  59.7 KiB/s | 153.0 KiB |  00m03s
[2/2] python3-pip-0:24.2-1.fc41.noarch                                                 100% | 211.3 KiB/s |   2.7 MiB |  00m13s
-------------------------------------------------------------------------------------------------------------------------------
[2/2] Total                                                                            100% | 205.9 KiB/s |   2.9 MiB |  00m14s
Running transaction
[1/4] Verify package files                                                             100% | 100.0   B/s |   2.0   B |  00m00s
[2/4] Prepare transaction                                                              100% |   2.0   B/s |   2.0   B |  00m01s
[3/4] Installing python3-pip-0:24.2-1.fc41.noarch                                      100% |   6.5 MiB/s |  11.7 MiB |  00m02s
[4/4] Installing davinci-helper-0:2.1.0-1.noarch                                       100% | 342.5 KiB/s |   1.0 MiB |  00m03s
>>> Running post-install scriptlet: davinci-helper-0:2.1.0-1.noarch
>>> Finished post-install scriptlet: davinci-helper-0:2.1.0-1.noarch
>>> Scriptlet output:
>>> Requirement already satisfied: moviepy in /usr/local/lib/python3.13/site-packages (2.0.0)
>>> Requirement already satisfied: decorator<6.0,>=4.0.2 in /usr/lib/python3.13/site-packages (from moviepy) (5.1.1)
>>> Requirement already satisfied: imageio<3.0,>=2.5 in /usr/local/lib/python3.13/site-packages (from moviepy) (2.36.0)
>>> Requirement already satisfied: imageio-ffmpeg>=0.2.0 in /usr/local/lib/python3.13/site-packages (from moviepy) (0.5.1)
>>> Requirement already satisfied: numpy>=1.25.0 in /usr/local/lib64/python3.13/site-packages (from moviepy) (2.1.3)
>>> Requirement already satisfied: proglog<=1.0.0 in /usr/local/lib/python3.13/site-packages (from moviepy) (0.1.10)
>>> Requirement already satisfied: python-dotenv>=0.10 in /usr/local/lib/python3.13/site-packages (from moviepy) (1.0.1)
>>> Requirement already satisfied: pillow<11.0,>=9.2.0 in /usr/local/lib64/python3.13/site-packages (from moviepy) (10.4.0)
>>> Requirement already satisfied: setuptools in /usr/lib/python3.13/site-packages (from imageio-ffmpeg>=0.2.0->moviepy) (69.2.
>>> Requirement already satisfied: tqdm in /usr/local/lib/python3.13/site-packages (from proglog<=1.0.0->moviepy) (4.67.0)
>>> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package 
>>> 
Complete!ng trigger-install scriptlet: man-db-0:2.12.1-2.fc41.x86_64c41.x86_64h

Running `pip install moviepy` doesn't solve the issue:

```
➜  ~ pip install moviepy
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: moviepy in /usr/local/lib/python3.13/site-packages (2.0.0)
Requirement already satisfied: decorator<6.0,>=4.0.2 in /usr/lib/python3.13/site-packages (from moviepy) (5.1.1)
Requirement already satisfied: imageio<3.0,>=2.5 in /usr/local/lib/python3.13/site-packages (from moviepy) (2.36.0)
Requirement already satisfied: imageio-ffmpeg>=0.2.0 in /usr/local/lib/python3.13/site-packages (from moviepy) (0.5.1)
Requirement already satisfied: numpy>=1.25.0 in /usr/local/lib64/python3.13/site-packages (from moviepy) (2.1.3)
Requirement already satisfied: proglog<=1.0.0 in /usr/local/lib/python3.13/site-packages (from moviepy) (0.1.10)
Requirement already satisfied: python-dotenv>=0.10 in /usr/local/lib/python3.13/site-packages (from moviepy) (1.0.1)
Requirement already satisfied: pillow<11.0,>=9.2.0 in /usr/local/lib64/python3.13/site-packages (from moviepy) (10.4.0)
Requirement already satisfied: setuptools in /usr/lib/python3.13/site-packages (from imageio-ffmpeg>=0.2.0->moviepy) (69.2.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/site-packages (from proglog<=1.0.0->moviepy) (4.67.0)
➜  ~ davinci-helper 
Traceback (most recent call last):
  File "/usr/bin/davinci-helper", line 5, in <module>
    from davinci_helper.main import main
  File "/usr/lib/python3.13/site-packages/davinci_helper/main.py", line 32, in <module>
    from .functions.gui.function_5_gui import function_5_class
  File "/usr/lib/python3.13/site-packages/davinci_helper/functions/gui/function_5_gui.py", line 36, in <module>
    from ..logic import conversion_settings
  File "/usr/lib/python3.13/site-packages/davinci_helper/functions/logic/conversion_settings.py", line 13, in <module>
    from moviepy.editor import VideoFileClip
ModuleNotFoundError: No module named 'moviepy.editor'
```
```

**Comment by H3rz3n** [comment]
Did you have upgraded from Fedora 40 ? Or you're using a fresh install of Fedora 41 ?

**Comment by Chevek** [comment]
> Hi, thank you for using DaVinci Helper. You are experiencing a very strange bug. MoviePy python module is supposed to be installed after the installation of DaVinci Helper as post-install script.
> 
> You can solve this issue installing it manually with PIP using `pip install moviepy`.

I tried, this does not change the error.

> 
> Can you please provide me more info about your Fedora config? Did you have installed the app from the COPR repository ?

It is a fresh installation of Fedora 41 on a new laptop. I used a post install script I wrote. You can find it here:
https://codeberg.org/Chevek/Fedora-GLF
Then I added the copr repository for davinci-helper.

As it seems moviepy is using ffmpeg, this is in this script:
- Adding rpmfusion repositories, 
- `sudo dnf swap -y ffmpeg-free ffmpeg --allowerasing` as documented here https://rpmfusion.org/Howto/Multimedia

**Comment by Chevek** [comment]
I tried instalaing Fedora 41 Workstation in a VM using GNOME Boxes, with just default repositories, did a `sudo dnf update`, installed the copr repositori, installed davinci-helper and got the same error. Thus my post installation script is not to blame here.

```
$ sudo dnf install davinci-helper
Mise à jour et chargement des dépôts :
Dépôts chargés.
Paquet                                                                                                   Architecture           Version                                                                                                  Dépôt                                                                         Taille
Installation de :
 davinci-helper                                                                                          noarch                 2.1.0-1                                                                                                  copr:copr.fedorainfracloud.org:herzen:davinci-helper                         1.0 MiB
Installation des dépendances :
 python3-pip                                                                                             noarch                 24.2-1.fc41                                                                                              fedora                                                                      11.4 MiB

Résumé de la transaction :
 Installation :      2 paquets

La taille totale des paquets entrants est de 3 MiB. Un téléchargement de 3 MiB est nécessaire.
Après cette opération, 12 MiB supplémentaires seront utilisés (+12 MiB, -0 B).
Is this ok [y/N]: y
[1/2] python3-pip-0:24.2-1.fc41.noarch                                                                                                                                                                                                                                               100% |  17.0 MiB/s |   2.7 MiB |  00m00s
[2/2] davinci-helper-0:2.1.0-1.noarch                                                                                                                                                                                                                                                100% | 731.9 KiB/s | 153.0 KiB |  00m00s
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[1/3] https://download.copr.fedorainfracloud.org/results/herzen/davinci-helper/pubkey.gpg                                                                                                                                                                                            100% |  45.4 KiB/s |   1.0 KiB |  00m00s
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[3/3] Total                                                                                                                                                                                                                                                                          100% |   4.6 MiB/s |   2.9 MiB |  00m01s
Importation de la clé PGP 0x6209BFEC :
 UserID     : "herzen_davinci-helper (None) <herzen#davinci-helper@copr.fedorahosted.org>"
 Empreinte  : 75AE2631E2FB5BAE6F2BF162DD29B6036209BFEC
 De         : https://download.copr.fedorainfracloud.org/results/herzen/davinci-helper/pubkey.gpg
Is this ok [y/N]: y
La clé a été importée avec succès.
[1/4] Vérifier les fichiers des paquets                                                                                                                                                                                                                                             100% | 285.0   B/s |   2.0   B |  00m00s
[2/4] Préparer la transaction                                                                                                                                                                                                                                                       100% |  15.0   B/s |   2.0   B |  00m00s
[3/4] Installation de python3-pip-0:24.2-1.fc41.noarch                                                                                                                                                                                                                               100% |  40.5 MiB/s |  11.7 MiB |  00m00s
[4/4] Installation de davinci-helper-0:2.1.0-1.noarch                                                                                                                                                                                                                                100% | 339.4 KiB/s |   1.0 MiB |  00m03s
>>> Exécution du scriptlet post-install : davinci-helper-0:2.1.0-1.noarch
>>> Scriptlet post-install terminé : davinci-helper-0:2.1.0-1.noarch
>>> Sortie du scriptlet :
>>> Collecting moviepy
>>>   Downloading moviepy-2.0.0-py3-none-any.whl.metadata (6.4 kB)
>>> Collecting decorator<6.0,>=4.0.2 (from moviepy)
>>>   Downloading decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
>>> Collecting imageio<3.0,>=2.5 (from moviepy)
>>>   Downloading imageio-2.36.0-py3-none-any.whl.metadata (5.2 kB)
>>> Collecting imageio-ffmpeg>=0.2.0 (from moviepy)
>>>   Downloading imageio_ffmpeg-0.5.1-py3-none-manylinux2010_x86_64.whl.metadata (1.6 kB)
>>> Collecting numpy>=1.25.0 (from moviepy)
>>>   Downloading numpy-2.1.3-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
>>> Collecting proglog<=1.0.0 (from moviepy)
>>>   Downloading proglog-0.1.10-py3-none-any.whl.metadata (639 bytes)
>>> Collecting python-dotenv>=0.10 (from moviepy)
>>>   Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
>>> Collecting pillow<11.0,>=9.2.0 (from moviepy)
>>>   Downloading pillow-10.4.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
>>> Requirement already satisfied: setuptools in /usr/lib/python3.13/site-packages (from imageio-ffmpeg>=0.2.0->moviepy) (69.2.0)
>>> Collecting tqdm (from proglog<=1.0.0->moviepy)
>>>   Downloading tqdm-4.67.0-py3-none-any.whl.metadata (57 kB)
>>> Downloading moviepy-2.0.0-py3-none-any.whl (122 kB)
>>> Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
>>> Downloading imageio-2.36.0-py3-none-any.whl (315 kB)
>>> Downloading imageio_ffmpeg-0.5.1-py3-none-manylinux2010_x86_64.whl (26.9 MB)
>>>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.9/26.9 MB 102.7 MB/s eta 0:00:00
>>> Downloading numpy-2.1.3-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
>>>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 101.5 MB/s eta 0:00:00
>>> Downloading pillow-10.4.0-cp313-cp313-manylinux_2_28_x86_64.whl (4.5 MB)
>>>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 97.0 MB/s eta 0:00:00
>>> Downloading proglog-0.1.10-py3-none-any.whl (6.1 kB)
>>> Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
>>> Downloading tqdm-4.67.0-py3-none-any.whl (78 kB)
>>> Installing collected packages: tqdm, python-dotenv, pillow, numpy, imageio-ffmpeg, decorator, proglog, imageio, moviepy
>>>   WARNING: The script tqdm is installed in '/usr/local/bin' which is not on PATH.
>>>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>>>   WARNING: The script dotenv is installed in '/usr/local/bin' which is not on PATH.
>>>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>>>   WARNING: The scripts f2py and numpy-config are installed in '/usr/local/bin' which is not on PATH.
>>>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>>>   WARNING: The scripts imageio_download_bin and imageio_remove_bin are installed in '/usr/local/bin' which is not on PATH.
>>>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>>> Successfully installed decorator-5.1.1 imageio-2.36.0 imageio-ffmpeg-0.5.1 moviepy-2.0.0 numpy-2.1.3 pillow-10.4.0 proglog-0.1.10 python-dotenv-1.0.1 tqdm-4.67.0
>>> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what
>>> 
Terminé !tion du scriptlet trigger-install : man-db-0:2.12.1-2.fc41.x86_64c41.x86_64h
chevek@fedora:~$ davinci-helper 
Traceback (most recent call last):
  File "/usr/bin/davinci-helper", line 5, in <module>
    from davinci_helper.main import main
  File "/usr/lib/python3.13/site-packages/davinci_helper/main.py", line 32, in <module>
    from .functions.gui.function_5_gui import function_5_class
  File "/usr/lib/python3.13/site-packages/davinci_helper/functions/gui/function_5_gui.py", line 36, in <module>
    from ..logic import conversion_settings
  File "/usr/lib/python3.13/site-packages/davinci_helper/functions/logic/conversion_settings.py", line 13, in <module>
    from moviepy.editor import VideoFileClip
ModuleNotFoundError: No module named 'moviepy.editor'
chevek@fedora:~$ 
```

**Comment by TarsiSurdi** [comment]
> Did you have upgraded from Fedora 40 ? Or you're using a fresh install of Fedora 41 ?
> 
> What happens if you use `pip install --target=/usr/lib/python3.X/site-packages moviepy` ?

I'll be trying that command out later tomorrow in order to see if the app launches. I did recently upgrade from 40 to 41 (not a fresh install) but I didn't have `davinci-helper` installed on it before upgrading.

Since then I've been able to install DaVinci through DistroBox, will your app mess up with that setup if it launches?

**Comment by H3rz3n** [comment]
Hi everyone, I was able to reproduce the bug and I'm currently working to fix it today. Thank you for the support and for using DaVinci Helper ! (^_^)

**Comment by H3rz3n** [comment]
I've fixed the issue, there was a problem with the moviepy  API. There was an update of moviepy with some breaking change that I didn't know. Now I've fixed the problem and I'm working on a version that will rely only on FFPROBE to ensure more reliability in the future. Thank you all for supporting and using DaVinci Helper (^_^).
