### ISSUE TITLE
[BUG] [VIDEO-CONVERTER] Video Converter error

### ISSUE THREAD

**Issue by diegotonetti99** [H3rz3n/davinci-helper#31]
When trying to load videos with file paths that contain white spaces in the file paths the conversion gets stuck.
The video path is ``` \home\diego\Videos\Concerto Natale\video.mp4```.
Looking at the terminal log reports 
```
Exception in thread Thread-2 (getting_ffmpeg_file_settings):
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/davinci_helper/functions/logic/conversion_settings.py", line 151, in get_file_info
    raise ValueError(f"ffprobe error: {result.stderr.strip()}")
ValueError: ffprobe error: Argument 'Natale' provided as input filename, but '/home/diego/Videos/Concerto' was already specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/lib64/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/davinci_helper/functions/gui/function_5_gui.py", line 639, in getting_ffmpeg_file_settings
    self.video_settings_list, self.audio_settings, self.total_file_weight, self.unsupported_file_list, self.duration_list = conversion_settings.calculate_disk_space(self.file_path_list, self.video_quality, self.audio_quality)
                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/davinci_helper/functions/logic/conversion_settings.py", line 66, in calculate_disk_space
    width, height, duration, fps = get_file_info(file)
                                   ~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/davinci_helper/functions/logic/conversion_settings.py", line 170, in get_file_info
    raise RuntimeError(f"Failed to get video info: {e}")
RuntimeError: Failed to get video info: ffprobe error: Argument 'Natale' provided as input filename, but '/home/diego/Videos/Concerto' was already specified.
^CTraceback (most recent call last):

```
Renaming the folder by removing the white space ``` \home\diego\Videos\Concerto_Natale\video.mp4```is a workaround.

**Comment by H3rz3n** [comment]
Hi ! Thank you for using DaVinci Helper. I'm sorry to hear that you're experiencing a bug. I've understand what's causing the problem and I will fix it in the next release. Grazie per la pazienza e per aver usato DaVinci Helper ! (^_^)

**Comment by H3rz3n** [comment]
Thank you for your patience, I've understand what's causing the problem and I fixed it the release v2.3.2. Thank you for letting me know (^_^) !
